permissions:
  contents: read
on:
  push:
    branches: [main]
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
name: deploy
jobs:
  build_and_deploy:
    runs-on: self-hosted
    name: ubuntu build

    steps:
      - uses: actions/checkout@main
        with: 
          submodules: true

      - name: Checkout repo
        run: |
          yes | ./scripts/fetch_distribution_package.sh

      - name: Run the Yocto build
        run: |
          cd data
          ls -lah
          yes | source scripts/setup_env.sh
          bitbake aurora-image-core
          bitbake -c populate_sdk aurora-image-core


      - name: Create the SD card image
        run: |
          cd openstlinux-kirkstone/build-openstlinuxweston-stm32mp1/tmp-glibc/deploy/images/stm32mp1/scripts
          ./create_sdcard_from_flashlayout.sh ../flashlayout_aurora-image-core/extensible/FlashLayout_sdcard_stm32mp157c-dk2-extensible.tsv

      - name: Save the SD card image as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: sd_card_image
          path: data/openstlinux-kirkstone/build-openstlinuxweston-stm32mp1/tmp-glibc/deploy/images/stm32mp1/FlashLayout_sdcard_stm32mp157c-dk2-extensible.raw

      - name: Save the SDK as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: sdk
          path: data/openstlinux-kirkstone/build-openstlinuxweston-stm32mp1/tmp-glibc/deploy/sdk/


